project:
  type: website

website:
  title: "marten w."
  favicon: images/logo.ico
  open-graph: true
  site-url: https://martenw.com/
  search: false
  navbar:
    logo: images/logo.webp
    logo-alt: "logo"
    title: "marten w."
    collapse-below: lg
    right: 
      - text: PROJECTS
        href: projects/index.qmd
      - text: BLOG
        href: blog/index.qmd
      - text: NOTES
        href: https://vwl.martenw.com
      - text: ABOUT
        href: about.qmd
      - text: CONTACT
        href: contact.qmd
      

  page-navigation: true

  back-to-top-navigation: false

  page-footer:
    left: |
      marten w. &copy; 2024
    center:
      - href: https://github.com/skriptum
        icon: github
        aria-label: GitHub
      - href: https://www.linkedin.com/in/marten-w
        icon: linkedin
        aria-label: LinkedIn
      - href: https://bsky.app/profile/mwd.bsky.social
        icon: twitter
        aria-label: bluesky

    right: |
      [Contact](/contact.qmd)

format:
  html:
    theme: [mw-custom.scss]
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px
link-external-icon: false
link-external-newwindow: true

execute: 
  freeze: auto