project:
  type: website

website:
  #title: "Marten Walk"
  favicon: images/logo.ico
  open-graph: true
  site-url: https://martenw.com/
  search: false
  navbar:
    logo: images/logo.webp
    logo-alt: "logo"
    title: ""
    collapse-below: sm
    right: 
      - text: PROJECTS
        href: projects/index.qmd
      - text: BLOG
        href: blog/index.qmd
      - text: ABOUT
        href: about.qmd
      - text: CONTACT
        href: contact.qmd


  page-navigation: true

  back-to-top-navigation: false

  page-footer:
    center:
      - href: https://github.com/skriptum
        icon: github
        aria-label: GitHub
      - href: https://www.linkedin.com/in/marten-w
        icon: linkedin
        aria-label: LinkedIn
      - href: https://bsky.app/profile/mwd.bsky.social
        icon: twitter
        aria-label: bluesky
    left: 
      - text: "© 2021-2024"
    right:
      - text: "Built with Quarto, inspired by FT"

format:
  html:
    theme: [mw-custom.scss]
    toc: true
    grid:
      body-width: 800px
    html-math-method: katex

#for transparency in plots in ggplot! see in Test 
knitr: 
  opts_chunk:
    dev: svg
    dev.args: { bg: "transparent" }

link-external-icon: false
link-external-newwindow: true

execute: 
  freeze: auto