project:
  type: website

website:
  #title: "Marten Walk"
  favicon: images/favicon.ico
  open-graph: 
    site-name: "Marten Walk"
    image: images/preview-og.jpg
    description: "econ student interested in monetary theory, inequality and the history of economic thought"
  site-url: https://martenw.com/
  search: false
  navbar:
    logo: images/logo.webp
    logo-alt: "logo"
    title: ""
    collapse-below: lg
    right: 
      - text: PROJECTS
        href: projects/index.qmd
      - text: BLOG
        href: "https://blog.martenw.com/"
      # - text: now
      #  href: now/index.qmd
      - text: ABOUT
        href: about.qmd
      - text: CONTACT
        href: contact.qmd


  page-navigation: true

  back-to-top-navigation: false

  page-footer:
    center:
      - href: https://to.martenw.com/github
        icon: github
        aria-label: GitHub
      - href: https://to.martenw.com/linkedin
        icon: linkedin
        aria-label: LinkedIn
      # - href: https://to.martenw.com/bsky
      #   icon: twitter
      #   aria-label: bluesky
    left: 
      - text: "© 2021-2025 Marten Walk"
    right:
      - href: colophon.qmd
        text: Colophon

format:
  html:
    theme: [mw-custom.scss]
    toc: true
    grid:
      body-width: 800px
    html-math-method: katex
    include-in-header: 
      text: |
        <script type="application/ld+json">
        {
          "@context": "https://schema.org/",
          "@type": "Person",
          "name": "Marten Walk",
          "url": "https://martenw.com",
          "alternateName": "Marten Walk",
          "description": "Economist",
          "image": "",
          "sameAs": [
            "https://de.linkedin.com/in/marten-walk",
            "https://bsky.app/profile/mwd.bsky.social",
            "https://github.com/skriptum"
          ],
          "jobTitle": "Economist"  
        }
        "alumniOf": [
            {
            "@type": "CollegeOrUniversity",
            "name": "University of Halle",
            "sameAs": "https://en.wikipedia.org/wiki/Martin_Luther_University_Halle-Wittenberg"
            }
          ],
        </script>
        <script defer src="https://cloud.umami.is/script.js" data-website-id="e9146946-1847-401b-98ea-d1d9981a1b02"></script>

#for transparency in plots in ggplot! see in Test 
knitr: 
  opts_chunk:
    dev: svg
    dev.args: { bg: "transparent" }

link-external-icon: false
link-external-newwindow: true

execute: 
  freeze: auto